name: 'Audit action'
description: 'Audits dependencies for vulnerabilities'
author: 'Taskworld'
inputs:
  path:
    description: 'Target path for the audit'
  package-manager:
    description: 'Package manager (pnpm or yarn)'
  identifier:
    description: 'Name of service/repo'
  failureLevel:
    description: 'Severity level causing audit to fail'
runs:
  using: 'node16'
  main: 'dist/index.js'
