name: 'Audit action'
description: 'Audits dependencies for vulnerabilities'
author: 'Taskworld'
inputs:
  package-name:
    description: 'name of the service or package'
    required: true
  failure-level:
    description: 'Severity level causing audit to fail'
    default: 'low'
  package-manager:
    description: 'Package manager (pnpm or yarn)'
    default: 'pnpm'
  path:
    description: 'Target path for the audit'
runs:
  using: 'node20'
  main: 'dist/index.js'
