name: Create release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create_release:
    name: releasing a new version
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: check package.json version changed
        id: check
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] || git diff --name-only HEAD~1 HEAD | grep -q '^package.json$'; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: new package.json version
        if: steps.check.outputs.changed == 'true'
        id: version
        run: echo "result=$(jq -er '.version' package.json)" >> "$GITHUB_OUTPUT"

      - uses: softprops/action-gh-release@v3
        if: steps.check.outputs.changed == 'true'
        with:
          tag_name: ${{ format('v{0}', steps.version.outputs.result) }}
